# This is a basic workflow to help you get started with Actions

name: Data Extraction

# Controls when the workflow will run
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.1.3'
          
      - run: |
            python -m pip install --upgrade pip
            pip install pandas numpy
            
      - run: |
          R -e 'install.packages("BiocManager")'
          R -e 'BiocManager::install("rcellminer")'
          
      - run: |
           Rscript code/data_extraction.r
           python code/nci60_to_ccle.py data/nci60Act.csv
           python code/testdata_extraction.py data/PubChemIDToSmiles.txt data/PubChemID.csv data/nci60Act_ccle.csv

      - uses: actions/upload-artifact@v3
        with:
          path: |
            data/*
